#!/bin/bash

#
# This script support some ZenLive's cheatcodes.
#

. /etc/rc.conf
. /etc/rc.d/functions
. /usr/lib/liblinuxlive

# passwd: Change root's password at startup
newrootpass="`cmdline_value passwd`"
if [ "$newrootpass" = "ask" ]; then
    echo -ne "\nEnter new password for root: "
    read -s newrootpass
fi

if [ ! "$newrootpass" = "" ]; then
    echo "root:$newrootpass" | /usr/sbin/chpasswd
fi

AUTOCMD=$(cmdline_value "autoexec" | tr "~" " ")
if [ "$AUTOCMD" != "" ]; then
   echo "starting autoexec command: su --login -c \"$AUTOCMD\""
   su --login -c "$AUTOCMD"
fi

# ldconfig: Updates dynamic library cache. Useful when new modules are
# added to the live cd.
if [ "`cmdline_parameter ldconfig`" ]; then
    [[ -x /sbin/ldconfig ]] && /sbin/ldconfig
fi

depmod -a

if [ -x /usr/bin/update-desktop-database ]; then
	update-desktop-database -q
fi

if [ -x /usr/bin/update-mime-database ]; then
	update-mime-database /usr/share/mime
fi

chmod 440 /etc/sudoers

sed -i 's/archlive //' /etc/rc.conf
chmod -x /etc/rc.d/archlive
