#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright (C) 2008-2009 Francesco Piccinno
#
# Author: Francesco Piccinno <stack.box@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

import re
import sys
from collections import defaultdict

def analyze(num, log):
    rtargets = re.compile('^Targets \(\d{1,2}\)\:(.+?)\n\n', re.MULTILINE | re.DOTALL)
    rtotsize = re.compile('Total Installed Size\:\s*([^\s]*)\sMB')

    targets = rtargets.findall(log)
    totsize = rtotsize.findall(log)

    packages = defaultdict(list)

    for target, size in zip(targets, totsize):
        target = target.replace('\n', '')
        target = re.findall('\s*([^\s]+).+?\s', target)
        target.reverse()

        size = map(int, size.split('.'))
        size = size[0] * (1024 ** 2) + size[1] * (1024 ** 2 / 100)

        packages[size].append(target)

    keys = packages.keys()

    keys.sort()
    keys.reverse()

    for huge in keys[:num]:
        for targets in packages[huge]:
            mb = float(huge) / 1024 ** 2
            print '%.02f\t%s (%s)' % (mb, targets[0], (', '.join(targets[1:]))[:-2])

if __name__ == "__main__":
    if len(sys.argv) == 2:

        print '#' * 50
        print '# Analyzing %s' % sys.argv[1]
        print '#' * 50
        print

        try:
            analyze(10, open(sys.argv[1]).read())
        except:
            print 'Error!'
    else:
        print 'Usage: %s <paclogfile>' % sys.argv[0]

